name: Build and Push Docker Image

on:
  push:
    branches:
      - "main"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Build the Docker image
        run: docker build -f ./frontend/Dockerfile.basic -t ghcr.io/tomek62/frontend:${{ github.sha }} .

      - name: Log in to GitHub Container Registry
        run: echo ${{ secrets.GITHUB_TOKEN }} | docker login ghcr.io -u ${{ github.actor }} --password-stdin

      - name: Push the Docker image
        run: docker push ghcr.io/tomek62/frontend:${{ github.sha }}
